server:
  port: 8090

spring:
  graphql:
    graphiql: # enable graphiQL playground for UI query and execution via /graphiql
      enabled: true
#    websocket:
#      path: /graphql
#    path: /graphql
  
logging:
  level:
    com.it.graphql_gateway_skeleton: DEBUG
    org.dataloader: DEBUG
    org.springframework.graphql: DEBUG

# Downstream service endpoints (for demo purposes)
downstream:
  services:
    user-service: http://localhost:9001
    order-service: http://localhost:9002  
    product-service: http://localhost:9003
